# Generated by Django 4.2.6 on 2025-08-31 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Degree_name',
            fields=[
                ('degree_name', models.CharField(help_text='Enter Degree Name like B.Tech, B.Sc..etc', max_length=100, primary_key=True, serialize=False)),
                ('degree_duration', models.IntegerField(choices=[(1, '1 Years'), (2, '2 Years'), (3, '3 Years'), (4, '4 Years'), (5, '5 Years'), (6, '6 Years'), (7, '7 Years'), (8, '8 Years'), (9, '9 Years')])),
                ('degree_code', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Degree_Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_Program', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(help_text='Enter Department Name like CSE, ECE, EEE..etc', max_length=100)),
                ('degree_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.degree_name')),
            ],
            options={
                'unique_together': {('degree_name', 'department_name')},
            },
        ),
        migrations.AddField(
            model_name='degree_name',
            name='degree_program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='degree_name', to='academics.degree_program'),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(help_text='Enter Course Name like Computer Science Engineering..etc', max_length=100)),
                ('course_fee', models.CharField(help_text='Enter fee per Year', max_length=15)),
                ('course_code', models.CharField(help_text='Enter Course Code Here..', max_length=20)),
                ('degree_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_name', to='academics.degree_name')),
                ('department_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='academics.departments')),
            ],
        ),
        migrations.CreateModel(
            name='Semesters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_number', models.IntegerField(help_text='Enter which semester it is')),
                ('course_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='academics.course')),
            ],
            options={
                'unique_together': {('course_name', 'semester_number')},
            },
        ),
    ]
