# Generated by Django 4.2.6 on 2025-08-31 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(help_text='Enter Subject Name', max_length=100)),
                ('subject_code', models.CharField(help_text='Enter Unique Subject Code', max_length=20)),
                ('credits', models.IntegerField(help_text='Enter Credits for the Subject')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='academics.course')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='academics.semesters')),
            ],
            options={
                'unique_together': {('semester', 'subject_code')},
            },
        ),
    ]
